<template>
  <div id="settings-view" style="display: flex;">
    <div class="settings-sidebar">
      <div class="settings-sidebar-header">Settings</div>
      <ul class="settings-nav">
        <li v-for="sec in sections" :key="sec.id" :class="{ active: activeSection === sec.id }" @click="switchSection(sec.id)">{{ sec.label }}</li>
      </ul>
    </div>
    <div class="settings-content-wrapper">
      <div class="settings-topbar">
        <div class="settings-breadcrumbs">Settings &gt; <span>{{ currentSectionLabel }}</span></div>
        <button id="settings-close-btn" @click="$emit('close')">&times;</button>
      </div>
      <div class="settings-main-scroll">

        <!-- Credentials Section -->
        <div v-show="activeSection === 'settings-credentials'" class="settings-section">
          <h3 class="settings-section-title">Credentials</h3>
          <div class="setting-item">
            <label>Clist Username</label>
            <div class="setting-desc">Used for fetching upcoming contests from the clist.by API.</div>
            <input type="text" :value="appSettings.clistUsername" @input="save('clistUsername', $event.target.value)" placeholder="e.g. tourist" />
          </div>
          <div class="setting-item">
            <label>Clist API Key</label>
            <div class="setting-desc">Your secret API key from clist.by for contest data.</div>
            <input type="password" :value="appSettings.clistApiKey" @input="save('clistApiKey', $event.target.value)" placeholder="••••••••••••••••••••••••" />
          </div>
          <div class="setting-item">
            <label>Groq API Key</label>
            <div class="setting-desc">Required for the AI Debug Agent and Training Plan generation.</div>
            <input type="password" :value="appSettings.groqApiKey" @input="save('groqApiKey', $event.target.value)" placeholder="gsk_..." />
          </div>
        </div>

        <!-- Agent Behavior Section -->
        <div v-show="activeSection === 'settings-agent-behavior'" class="settings-section">
          <h3 class="settings-section-title">Agent Behavior</h3>
          <div class="setting-item">
            <label>Auto-trigger Debug Agent on Compile Error (CE)</label>
            <div class="setting-desc">Automatically analyze errors when code fails to compile.</div>
            <div class="checkbox-wrapper">
              <input type="checkbox" :checked="appSettings.autoTriggerCE" @change="save('autoTriggerCE', $event.target.checked)" />
              <span>Enable for CE</span>
            </div>
          </div>
          <div class="setting-item">
            <label>Auto-trigger Debug Agent on Runtime Error (RE)</label>
            <div class="setting-desc">Automatically analyze crashes or out-of-bounds access.</div>
            <div class="checkbox-wrapper">
              <input type="checkbox" :checked="appSettings.autoTriggerRE" @change="save('autoTriggerRE', $event.target.checked)" />
              <span>Enable for RE</span>
            </div>
          </div>
          <div class="setting-item">
            <label>Auto-trigger Debug Agent on Wrong Answer (WA)</label>
            <div class="setting-desc">Automatically ask AI to find logic flaws when answers mismatch.</div>
            <div class="checkbox-wrapper">
              <input type="checkbox" :checked="appSettings.autoTriggerWA" @change="save('autoTriggerWA', $event.target.checked)" />
              <span>Enable for WA</span>
            </div>
          </div>
          <div class="setting-item">
            <label>Auto-trigger Debug Agent on Time Limit Exceeded (TLE)</label>
            <div class="setting-desc">Ask AI for optimization suggestions when code is too slow.</div>
            <div class="checkbox-wrapper">
              <input type="checkbox" :checked="appSettings.autoTriggerTLE" @change="save('autoTriggerTLE', $event.target.checked)" />
              <span>Enable for TLE</span>
            </div>
          </div>
          <div class="setting-item" style="border-top: 1px solid var(--border-color); padding-top: 16px; margin-top: 16px;">
            <label>Agent Memory Profile</label>
            <div class="setting-desc">Tags generated by the Agent based on your recent debugging history.</div>
            <div class="agent-memory-tags">
              <span v-if="memoryRecords.length === 0" style="color: #8b949e; font-size: 13px;">No memory records found.</span>
              <span v-else v-for="record in memoryRecords" :key="record" class="memory-tag">{{ record }}</span>
            </div>
            <button class="vs-secondary-btn" @click="clearMemory">Clear Memory</button>
          </div>
        </div>

        <!-- FinOps & Quota Section -->
        <div v-show="activeSection === 'settings-finops'" class="settings-section">
          <h3 class="settings-section-title">FinOps & Quota</h3>
          <div class="setting-item">
            <label>Daily Token Budget</label>
            <div class="setting-desc">Set your maximum daily token limit for cost control.</div>
            <div class="vscode-slider-container">
              <input type="range" id="setting-token-slider" min="1000" max="150000" step="1000" :value="appSettings.tokenBudget" @input="updateBudget($event.target.value)" />
              <input type="number" class="vscode-input" min="1000" max="150000" step="1000" :value="appSettings.tokenBudget" @change="updateBudget($event.target.value)" />
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import { invoke } from '@tauri-apps/api/core';
import { Store } from '@tauri-apps/plugin-store';
import { appSettings, updateStoreValue, updateTokenMonitorUI } from '../store';

defineEmits(['close']);

const sections = [
  { id: 'settings-credentials', label: 'Credentials' },
  { id: 'settings-agent-behavior', label: 'Agent Behavior' },
  { id: 'settings-finops', label: 'FinOps & Quota' }
];
const activeSection = ref('settings-credentials');
const currentSectionLabel = computed(() => sections.find(s => s.id === activeSection.value)?.label || '');
const memoryRecords = ref([]);

function switchSection(id) { activeSection.value = id; }

function save(key, value) { updateStoreValue(key, value); }

function updateBudget(val) {
  const parsed = parseInt(val) || 50000;
  updateStoreValue('tokenBudget', parsed);
  updateTokenMonitorUI();
}

async function loadMemory() {
  try {
    // Attempting to read via Rust command which handles file paths and parsing reliably
    const memory = await invoke('get_agent_memory');
    memoryRecords.value = memory && memory.length > 0 ? memory : [];
    
    // Optionally check via Store if needed for persistence monitoring, 
    // but the backend already manages .aceey_memory.json directly.
    const memoryStore = new Store('.aceey_memory.json');
    console.log("Memory Store initialized:", memoryStore.path);
  } catch (e) {
    console.error("Failed to load agent memory:", e);
  }
}

async function clearMemory() {
  try {
    await invoke('clear_agent_memory');
    memoryRecords.value = [];
    alert("Agent memory has been cleared!");
  } catch (e) {
    console.error("Failed to clear memory:", e);
  }
}

onMounted(() => { loadMemory(); });
</script>

